---
- hosts: jenkins-master
  become: true
  tasks: 
   - name: Adding Jenkins key
     apt_key: 
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      state: present

   - name: Adding Jenkins Repo
     apt_repository: 
      repo:  'echo deb https://pkg.jenkins.io/debian-stable binary/'
      state: present

   - name: Installing Java
     apt: 
      name: openjdk-11-jre
      state: present

   - name: Install Jenkins
     apt: 
      name: jenkins
      state: present

   - name: Starting Jenkins Service
     service: 
      name: jenkins
      state: started

   - name: Enabling Jenkins Service at boot time
     service: 
      name: jenkins
      enabled: yes
 ...         
